version: '3.8'

services:

  api:
    build: .
    command:
      [
        'sh',
        '-c',
        # sleep so db has time to startup
        'sleep 10 && pip install debugpy && python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
      ]
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 5678:5678
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/prisma
    depends_on:
      - db

  db:
    image: postgres:13.4
    volumes:
      - .pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prisma
